route:
  receiver: slack_default
  group_wait: 10s
  group_interval: 20s
  repeat_interval: 30s
  routes:
    - match:
        severity: critical
      receiver: slack_critical

receivers:
  - name: slack_default
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/<CHANGE_URL_HERE>'
        text: "{{ .CommonAnnotations.description }}"
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'

  - name: slack_critical
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/<CHANGE_URL_HERE>'
        text: "{{ .CommonAnnotations.description }}"
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
